<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ApplicationManifest Condition="'$(RuntimeIdentifier)' == 'win-x64'">app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../MateViewGuardian.Core/MateViewGuardian.Core.csproj" />
    <ProjectReference Include="../MateViewGuardian.Platform/MateViewGuardian.Platform.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets/guardian.svg" />
    <AvaloniaResource Include="Assets/guardian-*.png" />
    <AvaloniaResource Include="Assets/guardian-*.ico" />
  </ItemGroup>
</Project>
